import { PublicLayout } from "@/src/layouts";
import "@/styles/globals.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/700.css";
import "@fontsource/inter/900.css";
import { ThemeProvider } from "next-themes";
import type { AppProps } from "next/app";
import Head from "next/head";
import "react-toastify/dist/ReactToastify.css";
import { appWithTranslation } from 'next-i18next'

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Bundesliga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute="data-theme">
        <PublicLayout>
          <Component {...pageProps} />
        </PublicLayout>
      </ThemeProvider>
    </>
  );
};

export default appWithTranslation(App);
